from __future__ import annotations

import re


def quality_flags(*, text: str, html: str, content_type: str) -> tuple[str, ...]:
    flags: list[str] = []
    lowered = (text or html[:8000]).lower()
    if not text.strip(): flags.append("empty")
    if "�" in text or _mojibake_ratio(text) > 0.05: flags.append("mojibake")
    if any(marker in lowered for marker in ("generated by ai", "ai-generated", "由ai生成", "人工智能生成")):
        flags.append("ai_disclosure")
    if any(marker in lowered for marker in ("captcha", "g-recaptcha", "are you a human", "unusual traffic")):
        flags.append("captcha")
    if content_type and not any(kind in content_type.lower() for kind in ("text/", "application/xhtml", "application/xml", "application/json")):
        flags.append("unsupported_content_type")
    return tuple(flags)


def looks_like_app_shell(html: str, text: str, *, min_html_chars: int = 1000, max_text_chars: int = 300) -> bool:
    if len(html) < min_html_chars:
        return False
    lowered = html.lower()
    marker = bool(re.search(r"<(script|div)[^>]+(id=[\"'](?:root|app)|__next|webpack)", lowered))
    if not marker:
        return False
    visible = re.sub(r"<script\b[^>]*>.*?</script>", " ", html, flags=re.I | re.S)
    visible = re.sub(r"<style\b[^>]*>.*?</style>", " ", visible, flags=re.I | re.S)
    visible = re.sub(r"<[^>]+>", " ", visible)
    return len(re.sub(r"\s+", " ", visible).strip()) < max_text_chars


def _mojibake_ratio(text: str) -> float:
    if not text: return 0.0
    suspicious = sum(text.count(ch) for ch in ("Ã", "Â", "æ", "ð"))
    return suspicious / max(1, len(text))
