"""Host 侧记忆接口契约（Port / Protocol）。

这里定义的是 **host 唯一依赖** 的接口，而不是依赖 ``simple-harness-memory-sdk``
的具体实现。SDK 上线时由适配层把 SDK 后端接到本契约，host 其余代码不改。

边界（与 ``ARCHITECTURE/MEMORY_SDK_BOUNDARY.md`` 一致）：
- 进 SDK：``MemoryBackend``、``Embedder``、``WorldModelPort``。
- 留 host：ContextSnapshotStore（deskpet.agent）、CompanionMessageProjection
  （deskpet.companion）、coverage 规划（deskpet.agent.context_segment_store）。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable


# ── 宿主自有的最小数据模型 ─────────────────────────
# 这些是 host 侧的接口数据形状，刻意不 import SDK 类型，避免反向耦合。

@dataclass
class Message:
    id: int | None
    session_id: str
    role: str
    content: str
    created_at: float = 0.0
    # host 侧会话/工作流/工具调用的溯源元数据，SDK Message 必须能往返这些字段。
    root_run_id: str | None = None
    workflow_event_id: str | None = None
    tool_call_id: str | None = None
    salience: float = 0.0
    decay_rate: float = 0.02
    embedding: bytes | None = None
    is_summary: bool = False
    summary_of: str | None = None


@dataclass
class Fact:
    id: int | None
    subject: str
    key: str
    value: str
    category: str
    confidence: float
    evidence: str
    source_msg_id: int
    created_at: float
    pinned: bool = False
    superseded_by: int | None = None
    forgotten_at: float | None = None

    @property
    def is_active(self) -> bool:
        return self.superseded_by is None and self.forgotten_at is None


@dataclass
class Hit:
    message_id: int
    text: str
    score: float
    source: str
    session_id: str | None = None
    role: str | None = None
    created_at: float | None = None
    session_affinity: float = 1.0


# ── 宿主侧接口契约 ────────────────────────────────

@runtime_checkable
class MemoryBackend(Protocol):
    """记忆后端契约。SDK 后端通过结构类型满足此 Protocol。"""

    async def append_message(
        self,
        session_id: str,
        role: str,
        content: str,
        *,
        workflow_event_id: str | None = None,
        root_run_id: str | None = None,
        tool_call_id: str | None = None,
    ) -> int: ...

    async def get_recent_messages(self, session_id: str, limit: int = 20) -> list[Message]: ...

    async def get_message(self, message_id: int) -> Message | None: ...

    async def recall(
        self,
        query: str,
        session_id: str | None = None,
        limit: int = 10,
    ) -> list[Hit]: ...

    async def vector_search(self, query: str, limit: int = 20) -> list[Hit]: ...

    async def extract_facts(
        self,
        message_id: int,
        content: str,
        role: str,
    ) -> list[Fact]: ...

    async def get_facts(
        self,
        subject: str = "user",
        category: str | None = None,
        active_only: bool = True,
    ) -> list[Fact]: ...

    async def forget_fact(self, fact_id: int, reason: str = "") -> bool: ...

    async def get_digital_twin(self, subject: str = "user") -> Any: ...

    async def update_digital_twin(self, twin: Any) -> None: ...

    async def suggest_questions(self, subject: str = "user") -> list[str]: ...

    async def detect_inconsistencies(self, subject: str = "user") -> list[Any]: ...

    async def daily_decay(self) -> dict[str, int]: ...

    async def summarize_old_sessions(
        self,
        older_than_days: int = 7,
        max_sessions: int = 5,
    ) -> dict[str, int]: ...

    async def record_workspace_action(
        self,
        session_id: str,
        action_type: str,
        payload: dict,
    ) -> None: ...

    async def initialize(self) -> None: ...

    async def close(self) -> None: ...


@runtime_checkable
class SessionDB(Protocol):
    """host 侧会话账本契约（SessionDB，留 host，不进 SDK）。

    这是 host 的会话持久化 / 交付状态 / provider 绑定 / context usage / 目标与
    todo / companion ingress 账本，方法面远大于 MemoryBackend。它**不是**
    MemoryBackend 的薄适配器；两者只在消息存取处相交（append_message /
    get_recent_messages / initialize / close），其余方法由 host 自行实现。
    """

    # ── 与 MemoryBackend 相交的 4 个方法 ──────────────
    async def append_message(self, session_id: str, role: str, content: str) -> int: ...
    async def get_recent_messages(self, session_id: str, limit: int = 20) -> list[Any]: ...
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...

    # ── 会话 / 交付状态 ──────────────────────────────
    async def create_session(self, metadata: dict[str, Any] | None = None) -> str: ...
    async def ensure_session(self, *args: Any, **kwargs: Any) -> Any: ...
    async def bind_session_owner_if_absent(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_session_delivery_state(self, session_id: str) -> dict[str, Any]: ...
    async def tombstone_session(self, *args: Any, **kwargs: Any) -> Any: ...
    async def set_session_title(self, session_id: str, title: str) -> str: ...

    # ── 消息 / 检索 ──────────────────────────────────
    async def get_messages(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_message_role(self, msg_id: int) -> Any: ...
    async def get_message_routing_context(self, *args: Any, **kwargs: Any) -> Any: ...
    async def append_message_if_epoch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def search_fts(self, *args: Any, **kwargs: Any) -> Any: ...
    async def update_salience(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_recent(self, *args: Any, **kwargs: Any) -> Any: ...
    async def append(self, session_id: str, role: str, content: str) -> None: ...
    async def clear(self, session_id: str) -> None: ...
    async def list_turns(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete_turn(self, turn_id: int) -> bool: ...
    async def list_sessions(self) -> list[Any]: ...
    async def list_sessions_with_preview(self) -> list[dict[str, Any]]: ...

    # ── owner 记忆读取范围 ────────────────────────────
    async def capture_owner_memory_read_scope(self, *args: Any, **kwargs: Any) -> Any: ...
    async def recall_owner_messages_readonly(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── context usage ────────────────────────────────
    async def record_context_usage_sample(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_context_usage_history(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_context_usage_sample(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_context_usage_state(self, session_id: str) -> dict[str, Any]: ...
    async def set_context_usage_binding_state(self, *args: Any, **kwargs: Any) -> Any: ...
    async def advance_context_usage_binding_state_tx(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── provider binding ─────────────────────────────
    async def get_session_provider_binding(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_session_provider_binding_authority(self, *args: Any, **kwargs: Any) -> Any: ...
    async def set_session_provider_binding(self, *args: Any, **kwargs: Any) -> Any: ...
    async def inherit_session_provider_binding(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_code_session_provider_binding(self, *args: Any, **kwargs: Any) -> Any: ...
    async def set_code_session_provider_binding(self, *args: Any, **kwargs: Any) -> Any: ...
    async def clear_bindings_for_provider(self, provider_id: str) -> int: ...
    async def reconcile_provider_bindings(self, *args: Any, **kwargs: Any) -> Any: ...
    async def clear_all(self) -> int: ...

    # ── companion projection / ingress ───────────────
    async def append_user_message_with_growth_outbox(self, *args: Any, **kwargs: Any) -> Any: ...
    async def settle_companion_ingress_semantic_intent(self, *args: Any, **kwargs: Any) -> Any: ...
    async def read_companion_ingress_message_content(self, *args: Any, **kwargs: Any) -> Any: ...
    async def append_companion_projection_if_epoch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def append_projection_if_epoch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def relocate_projection_if_epoch(self, *args: Any, **kwargs: Any) -> Any: ...
    async def append_current_projection_if_absent(self, *args: Any, **kwargs: Any) -> Any: ...
    async def redact_projection_if_hash(self, *args: Any, **kwargs: Any) -> Any: ...
    async def record_companion_projection_redaction(self, *args: Any, **kwargs: Any) -> Any: ...
    async def claim_companion_ingress_outbox(self, *args: Any, **kwargs: Any) -> Any: ...
    async def settle_companion_ingress_outbox(self, *args: Any, **kwargs: Any) -> Any: ...
    async def set_companion_default_route(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_companion_projection_route(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_companion_projection(self, *args: Any, **kwargs: Any) -> Any: ...
    async def claim_companion_projection_route_outbox(self, *args: Any, **kwargs: Any) -> Any: ...
    async def settle_companion_projection_route_outbox(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── todo ─────────────────────────────────────────
    async def replace_session_todos(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_session_todos(self, session_id: str) -> list[dict[str, Any]]: ...
    async def replace_code_todos(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_code_todos(self, session_id: str) -> list[dict[str, Any]]: ...
    async def sync_workflow_code_todos(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete_code_todos(self, session_id: str) -> int: ...

    # ── code sessions / session plan ─────────────────
    async def upsert_code_session(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_code_sessions(self) -> list[dict[str, Any]]: ...
    async def delete_code_session(self, base_session_id: str) -> int: ...
    async def upsert_session_plan(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_session_plan(self, session_id: str) -> Any: ...
    async def clear_session_plan_awaiting(self, session_id: str) -> None: ...

    # ── goals / tasks ────────────────────────────────
    async def upsert_session_goal(self, *args: Any, **kwargs: Any) -> Any: ...
    async def project_goal_terminal(self, goal_id: str, status: str) -> bool: ...
    async def get_active_goals(self, session_id: str) -> list[dict[str, Any]]: ...
    async def list_active_goals(self) -> list[dict[str, Any]]: ...
    async def create_goal_task(self, *args: Any, **kwargs: Any) -> Any: ...
    async def get_goal_task(self, task_id: str) -> Any: ...
    async def list_goal_tasks(self, goal_id: str) -> list[dict[str, Any]]: ...
    async def update_goal_task(self, *args: Any, **kwargs: Any) -> Any: ...
    async def claim_ready_goal_task(self, *args: Any, **kwargs: Any) -> Any: ...

    # ── supervisor hints ─────────────────────────────
    async def append_supervisor_hint(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_supervisor_hints(self, *args: Any, **kwargs: Any) -> Any: ...
    async def count_supervisor_hints(self, *args: Any, **kwargs: Any) -> Any: ...


@runtime_checkable
class Embedder(Protocol):
    """host 侧向量化契约。

    注意：host 旧调用是 ``await embedder.encode(texts)`` + ``embedder.is_mock()``。
    SDK 提供的 Embedder 是同步 ``embed``/``embed_batch``，host 适配层负责
    sync→async 包装并补 ``is_mock``。
    """

    @property
    def dim(self) -> int: ...

    def is_mock(self) -> bool: ...

    async def encode(self, texts: list[str]) -> list[list[float]]: ...


@runtime_checkable
class WorldModelPort(Protocol):
    """世界对象契约（时间 / 事件 / 地理 / 知识边界）。"""

    async def get_temporal_context(self) -> Any: ...

    async def get_recent_events(self, days: int = 3) -> list[Any]: ...

    async def get_weather(self, location: str) -> Any | None: ...

    async def check_knowledge_boundary(self, query: str) -> Any | None: ...

    async def get_personalized_news(
        self,
        interests: list[str],
        categories: list[str] | None = None,
    ) -> list[Any]: ...
