# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0
"""Frozen source-column inventory for migration 26 (not runtime reflection).

Any future source column/reader/writer change must update this owner inventory
and the relevant migration, rather than silently falling outside invalidation.
"""

MISSION_TABLES = (
    "sources",
    "artifacts",
    "observations",
    "justification_sets",
    "support_members",
    "task_semantics",
    "method_instances",
    "requirements_revisions",
    "review_packages",
    "review_records",
    "criterion_evaluations",
    "acceptances",
    "goal_resolutions",
    "input_manifest_bindings",
    "plan_revisions",
    "plan_memberships",
    "method_child_occurrences",
    "order_constraints",
    "data_requirements",
    "bound_inputs",
    "obligations",
    "obligation_relations",
    "operation_identities",
    "operation_bindings",
    "operation_completion_specs",
    "operation_completion_scopes",
    "results",
    "actions",
    "approvals",
    "planning_lane_grants",
    "assurance_check_bindings",
    "assurance_criterion_policies",
    "assurance_review_record_bindings",
    "mission_policies",
    "planning_request_authority_bindings",
    "planning_operation_action_links",
    "operation_outcome_review_bindings",
    "operation_acceptance_scopes",
    "operation_payload_objects",
    "operation_intent_bindings",
    "acceptance_commit_receipts",
    "delivery_receipts",
    "acceptance_outputs",
    "claims",
)

GLOBAL_TABLES = ("method_contracts", "policy_versions", "policy_proposals", "policy_activations")

SOURCE_COLUMNS = {
    "events": (
        "seq",
        "event_id",
        "idempotency_key",
        "type",
        "trace_id",
        "mission_id",
        "task_id",
        "attempt_id",
        "actor_type",
        "actor_id",
        "payload_json",
        "created_at",
        "schema_version",
    ),
    "acceptance_commit_receipts": (
        "mission_id",
        "command_id",
        "kind",
        "subject_id",
        "intent_hash",
        "read_set_hash",
        "event_id",
        "output_identity_json",
        "detail_json",
        "applied_at",
    ),
    "acceptance_outputs": (
        "mission_id",
        "acceptance_id",
        "output_port",
        "artifact_id",
        "producer_occurrence",
        "producer_task_ref",
        "producer_result_id",
        "support_revision",
        "content_hash",
        "source_revision",
        "output_json",
        "recorded_at",
    ),
    "acceptances": (
        "acceptance_id",
        "mission_id",
        "task_id",
        "obligation_id",
        "review_record_id",
        "requirements_revision",
        "contract_revision",
        "input_manifest_hash",
        "validity",
        "accepted_at_ms",
        "content_hash",
        "acceptance_json",
        "created_at",
    ),
    "actions": (
        "action_key",
        "action_id",
        "version",
        "mission_id",
        "state",
        "json",
        "created_at",
        "updated_at",
    ),
    "approvals": (
        "request_id",
        "kind",
        "mission_id",
        "subject_key",
        "state",
        "version",
        "json",
        "created_at",
        "updated_at",
    ),
    "artifacts": (
        "artifact_id",
        "mission_id",
        "task_id",
        "attempt_id",
        "path",
        "content_hash",
        "version",
        "json",
        "created_at",
    ),
    "assurance_check_bindings": (
        "check_binding_id",
        "mission_id",
        "execution_ref_hash",
        "check_spec_hash",
        "subject_hash",
        "assertion_key",
        "binding_hash",
        "binding_json",
        "import_receipt_id",
        "created_at_ms",
    ),
    "assurance_criterion_policies": (
        "policy_id",
        "mission_id",
        "requirements_revision",
        "requirements_hash",
        "scope_hash",
        "policy_hash",
        "policy_json",
        "approval_receipt_id",
    ),
    "assurance_review_record_bindings": (
        "record_id",
        "mission_id",
        "review_key",
        "source_turn_ref_hash",
        "raw_output_hash",
        "evidence_manifest_hash",
        "binding_hash",
        "binding_json",
        "import_receipt_id",
        "created_at_ms",
    ),
    "bound_inputs": (
        "mission_id",
        "plan_revision",
        "requirement_id",
        "input_binding_revision",
        "producer_result_id",
        "acceptance_id",
        "artifact_id",
        "content_hash",
        "source_revision",
        "binding_json",
        "created_at",
    ),
    "claims": (
        "claim_id",
        "mission_id",
        "result_id",
        "status",
        "version",
        "json",
        "updated_at",
        "key",
    ),
    "criterion_evaluations": (
        "review_id",
        "criterion_id",
        "mission_id",
        "package_id",
        "verdict",
        "check_execution",
        "check_receipt_hash",
        "outcome_json",
        "created_at",
    ),
    "data_requirements": (
        "mission_id",
        "plan_revision",
        "requirement_id",
        "producer_occurrence",
        "output_port",
        "consumer_occurrence",
        "input_port",
        "source_revision_policy",
        "requirement_json",
        "created_at",
    ),
    "delivery_receipts": (
        "mission_id",
        "command_id",
        "receipt_id",
        "acceptance_id",
        "stage",
        "observed_at_ms",
        "operation_id",
        "intent_hash",
        "receipt_json",
        "recorded_at",
    ),
    "goal_resolutions": (
        "resolution_id",
        "mission_id",
        "obligation_id",
        "goal_task_id",
        "requirements_version",
        "contract_revision",
        "method_instance_id",
        "review_receipt_id",
        "verdict",
        "validity",
        "adopted",
        "content_hash",
        "resolution_json",
        "created_at",
        "updated_at",
    ),
    "input_manifest_bindings": (
        "mission_id",
        "task_id",
        "manifest_hash",
        "attempt_id",
        "request_id",
        "input_binding_revision",
        "created_at",
    ),
    "input_manifests": ("manifest_hash", "origin_mission_id", "manifest_json", "created_at"),
    "justification_sets": (
        "set_id",
        "mission_id",
        "subject_kind",
        "subject_id",
        "member_revision",
        "member_digest",
        "rule_ref",
        "detail_json",
        "created_at",
    ),
    "method_child_occurrences": (
        "instance_id",
        "slot_key",
        "mission_id",
        "occurrence_id",
        "obligation_id",
        "goal_occurrence_id",
        "requiredness",
        "reuse_policy",
        "binding_json",
        "created_at",
    ),
    "method_contracts": (
        "method_id",
        "method_version",
        "content_hash",
        "registry_status",
        "author",
        "trial_scope_mission",
        "registration_json",
        "contract_json",
        "created_at",
        "updated_at",
    ),
    "method_instances": (
        "mission_id",
        "instance_id",
        "goal_task_id",
        "goal_occurrence_id",
        "obligation_id",
        "method_id",
        "method_version",
        "method_content_hash",
        "plan_revision",
        "state",
        "parameters_digest",
        "draft_json",
        "created_at",
        "updated_at",
    ),
    "mission_policies": ("mission_id", "version_id", "source", "provider_kind", "json", "bound_at"),
    "obligation_relations": (
        "mission_id",
        "parent_obligation_id",
        "child_obligation_id",
        "kind",
        "active_revision",
        "detail_json",
        "created_at",
    ),
    "obligations": (
        "mission_id",
        "obligation_id",
        "goal_signature_id",
        "scope",
        "requiredness",
        "lifecycle",
        "resolution_ref",
        "parent_obligation_id",
        "budget_lineage_ref",
        "failure_count",
        "spent_tokens",
        "spent_attempts",
        "fuel_limit",
        "fuel_used",
        "fuel_remaining",
        "demand_admitted",
        "obligation_json",
        "created_at",
        "updated_at",
    ),
    "observations": (
        "observation_id",
        "mission_id",
        "proposition_key",
        "polarity",
        "scope_id",
        "source_kind",
        "source_id",
        "coverage",
        "observer_id",
        "observed_at_ms",
        "recorded_at_ms",
        "query_watermark_ms",
        "valid_until_ms",
        "observation_json",
        "created_at",
    ),
    "operation_acceptance_scopes": (
        "acceptance_id",
        "mission_id",
        "completion_scope_id",
        "contribution_kind",
        "scope_hash",
        "contribution_hash",
        "document_json",
        "outcome_binding_id",
        "delivery_receipt_id",
        "producer_receipt_id",
        "created_at_ms",
    ),
    "operation_bindings": (
        "principal_id",
        "scope_id",
        "operation_occurrence_id",
        "operation_id",
        "request_hash",
        "mission_id",
        "obligation_id",
        "connector_id",
        "connector_version",
        "operation_kind",
        "envelope_hash",
        "envelope_json",
        "created_at",
    ),
    "operation_completion_scopes": (
        "scope_id",
        "mission_id",
        "plan_revision",
        "occurrence_id",
        "task_id",
        "task_binding_revision",
        "task_contract_hash",
        "spec_id",
        "spec_hash",
        "scope_hash",
        "document_json",
        "plan_receipt_id",
        "created_at_ms",
    ),
    "operation_completion_specs": (
        "spec_id",
        "mission_id",
        "requirements_revision",
        "requirements_hash",
        "spec_hash",
        "document_json",
        "approval_receipt_id",
        "created_at_ms",
    ),
    "operation_identities": (
        "operation_id",
        "mission_id",
        "request_hash",
        "envelope_hash",
        "envelope_json",
        "created_at",
    ),
    "operation_intent_bindings": (
        "intent_id",
        "mission_id",
        "tenant_id",
        "principal_id",
        "scope_id",
        "source_kind",
        "origin_receipt_id",
        "slot_key",
        "submission_receipt_id",
        "submission_hash",
        "supersedes_intent_id",
        "producer_task_id",
        "producer_occurrence_id",
        "obligation_id",
        "source_result_id",
        "source_attempt_id",
        "candidate_artifact_id",
        "candidate_file_hash",
        "task_contract_revision",
        "task_contract_hash",
        "requirements_revision",
        "requirements_hash",
        "plan_revision",
        "plan_snapshot_hash",
        "parameters_object_id",
        "parameters_content_hash",
        "params_hash",
        "effect_object_id",
        "effect_content_hash",
        "proposal_object_id",
        "proposal_content_hash",
        "request_hash",
        "review_package_id",
        "binding_json",
        "created_at_ms",
    ),
    "operation_outcome_review_bindings": (
        "binding_id",
        "mission_id",
        "spec_id",
        "spec_hash",
        "effect_key",
        "completion_scope_id",
        "intent_id",
        "operation_id",
        "operation_occurrence_id",
        "action_key",
        "action_version",
        "request_hash",
        "effect_contract_hash",
        "source_manifest_hash",
        "binding_hash",
        "document_json",
        "review_package_id",
        "producer_receipt_id",
        "created_at_ms",
    ),
    "operation_payload_objects": (
        "object_id",
        "mission_id",
        "object_kind",
        "object_revision",
        "content_hash",
        "byte_length",
        "media_type",
        "storage_uri",
        "source_receipt_id",
        "created_at_ms",
    ),
    "order_constraints": (
        "mission_id",
        "plan_revision",
        "before_occurrence",
        "after_occurrence",
        "release_condition",
        "constraint_json",
        "created_at",
    ),
    "plan_memberships": (
        "mission_id",
        "revision",
        "occurrence_id",
        "task_id",
        "obligation_id",
        "instance_id",
        "form",
        "requiredness",
        "adopted",
        "member_json",
        "created_at",
    ),
    "plan_revisions": (
        "mission_id",
        "revision",
        "state",
        "base_revision",
        "snapshot_hash",
        "delta_id",
        "read_set_json",
        "created_at",
        "updated_at",
    ),
    "planning_lane_grants": (
        "grant_id",
        "revision",
        "mission_id",
        "tenant_id",
        "scope_id",
        "grantee_id",
        "issuer_id",
        "issuer_command_id",
        "issuer_receipt_hash",
        "active",
        "allowed_decisions_json",
        "policy_hash",
        "not_before_ms",
        "expires_at_ms",
        "content_hash",
        "grant_json",
    ),
    "planning_operation_action_links": (
        "operation_id",
        "request_hash",
        "operation_occurrence_id",
        "mission_id",
        "envelope_hash",
        "principal_id",
        "scope_id",
        "obligation_id",
        "producer_task_id",
        "producer_htn_occurrence_id",
        "producer_contract_revision",
        "producer_plan_revision",
        "action_key",
        "action_id",
        "action_version",
        "params_hash",
        "idempotency_key",
        "provenance_receipt_id",
        "link_hash",
        "link_json",
    ),
    "planning_request_authority_bindings": (
        "request_id",
        "mission_id",
        "tenant_id",
        "scope_id",
        "planner_principal_id",
        "grant_id",
        "grant_revision",
        "grant_hash",
        "binding_hash",
        "binding_json",
    ),
    "policy_activations": ("seq", "version_id", "action", "json", "created_at"),
    "policy_proposals": ("proposal_id", "version_id", "state", "json", "created_at", "updated_at"),
    "policy_versions": (
        "version_id",
        "params_hash",
        "source",
        "status",
        "json",
        "created_at",
        "updated_at",
    ),
    "requirements_revisions": (
        "mission_id",
        "revision",
        "revision_id",
        "content_hash",
        "authority_subject",
        "revision_json",
        "created_at",
    ),
    "results": (
        "result_id",
        "attempt_id",
        "task_id",
        "mission_id",
        "turn_id",
        "result_hash",
        "verification_state",
        "verdict",
        "json",
        "received_at",
        "updated_at",
    ),
    "review_packages": (
        "package_id",
        "mission_id",
        "purpose",
        "review_account",
        "obligation_id",
        "subject_kind",
        "subject_id",
        "requirements_revision",
        "input_manifest_hash",
        "method_instance_id",
        "package_hash",
        "package_json",
        "created_at",
    ),
    "review_records": (
        "record_id",
        "package_id",
        "mission_id",
        "purpose",
        "reviewer_agent_id",
        "reviewer_turn_id",
        "verdict",
        "evidence_manifest_hash",
        "official",
        "record_hash",
        "record_json",
        "created_at",
    ),
    "sources": (
        "mission_id",
        "tenant_id",
        "path",
        "version_hash",
        "kind",
        "trust",
        "registered_at",
        "superseded_by",
        "revoked",
        "revision",
    ),
    "support_members": (
        "set_id",
        "member_kind",
        "member_id",
        "mission_id",
        "polarity",
        "member_revision",
        "member_json",
        "created_at",
    ),
    "task_semantics": (
        "task_id",
        "binding_revision",
        "mission_id",
        "obligation_id",
        "form",
        "semantic_scope",
        "goal_signature_id",
        "operator_ref",
        "adopted_method_instance_id",
        "input_binding_revision",
        "dispatch_generation",
        "content_hash",
        "binding_json",
        "created_at",
    ),
    "validity_epochs": ("mission_id", "scope_id", "epoch", "bumped_by", "updated_at"),
    "verifications": (
        "verification_id",
        "result_id",
        "attempt_id",
        "layer",
        "status",
        "detail_json",
        "created_at",
    ),
}

SOURCE_PRIMARY_KEYS = {
    "events": ("seq",),
    "acceptance_commit_receipts": ("mission_id", "command_id"),
    "acceptance_outputs": ("acceptance_id", "output_port", "artifact_id"),
    "acceptances": ("acceptance_id",),
    "actions": ("action_key",),
    "approvals": ("request_id",),
    "artifacts": ("artifact_id",),
    "assurance_check_bindings": ("check_binding_id",),
    "assurance_criterion_policies": ("policy_id",),
    "assurance_review_record_bindings": ("record_id",),
    "bound_inputs": ("mission_id", "plan_revision", "requirement_id", "input_binding_revision"),
    "claims": ("claim_id",),
    "criterion_evaluations": ("review_id", "criterion_id"),
    "data_requirements": ("mission_id", "plan_revision", "requirement_id"),
    "delivery_receipts": ("mission_id", "command_id"),
    "goal_resolutions": ("resolution_id",),
    "input_manifest_bindings": ("mission_id", "task_id", "manifest_hash"),
    "input_manifests": ("manifest_hash",),
    "justification_sets": ("set_id",),
    "method_child_occurrences": ("instance_id", "slot_key"),
    "method_contracts": ("method_id", "method_version"),
    "method_instances": ("mission_id", "instance_id"),
    "mission_policies": ("mission_id",),
    "obligation_relations": ("mission_id", "parent_obligation_id", "child_obligation_id", "kind"),
    "obligations": ("mission_id", "obligation_id"),
    "observations": ("observation_id",),
    "operation_acceptance_scopes": ("acceptance_id",),
    "operation_bindings": ("principal_id", "scope_id", "operation_occurrence_id"),
    "operation_completion_scopes": ("scope_id",),
    "operation_completion_specs": ("spec_id",),
    "operation_identities": ("operation_id",),
    "operation_intent_bindings": ("intent_id",),
    "operation_outcome_review_bindings": ("binding_id",),
    "operation_payload_objects": ("object_id",),
    "order_constraints": ("mission_id", "plan_revision", "before_occurrence", "after_occurrence"),
    "plan_memberships": ("mission_id", "revision", "occurrence_id"),
    "plan_revisions": ("mission_id", "revision"),
    "planning_lane_grants": ("grant_id", "revision"),
    "planning_operation_action_links": ("operation_id",),
    "planning_request_authority_bindings": ("request_id",),
    "policy_activations": ("seq",),
    "policy_proposals": ("proposal_id",),
    "policy_versions": ("version_id",),
    "requirements_revisions": ("mission_id", "revision"),
    "results": ("result_id",),
    "review_packages": ("package_id",),
    "review_records": ("record_id",),
    "sources": ("mission_id", "path", "version_hash"),
    "support_members": ("set_id", "member_kind", "member_id"),
    "task_semantics": ("task_id", "binding_revision"),
    "validity_epochs": ("mission_id", "scope_id"),
    "verifications": ("verification_id",),
}

CROSS_MISSION_KEYS = {
    "events": (("seq",), ("event_id",), ("idempotency_key",)),
    "acceptance_outputs": (("acceptance_id", "output_port", "artifact_id"),),
    "acceptances": (("acceptance_id",), ("review_record_id",)),
    "actions": (("action_id", "version"), ("action_key",)),
    "approvals": (("request_id",),),
    "artifacts": (("artifact_id",), ("attempt_id", "path", "version")),
    "assurance_check_bindings": (("check_binding_id",),),
    "assurance_criterion_policies": (("policy_id",),),
    "assurance_review_record_bindings": (("record_id",),),
    "claims": (("claim_id",),),
    "criterion_evaluations": (("review_id", "criterion_id"),),
    "goal_resolutions": (("resolution_id",),),
    "justification_sets": (("set_id",),),
    "method_child_occurrences": (("instance_id", "slot_key"),),
    "obligations": (("obligation_id",),),
    "observations": (("observation_id",),),
    "operation_acceptance_scopes": (("acceptance_id",), ("outcome_binding_id",)),
    "operation_bindings": (
        ("operation_occurrence_id",),
        ("principal_id", "scope_id", "operation_occurrence_id"),
    ),
    "operation_completion_scopes": (("scope_id",),),
    "operation_completion_specs": (("spec_id",),),
    "operation_identities": (("operation_id",), ("operation_id", "request_hash")),
    "operation_intent_bindings": (
        ("intent_id",),
        ("review_package_id",),
        ("submission_receipt_id",),
    ),
    "operation_outcome_review_bindings": (("binding_id",), ("review_package_id",)),
    "operation_payload_objects": (("object_id",),),
    "planning_lane_grants": (("grant_id", "revision"), ("issuer_command_id",)),
    "planning_operation_action_links": (
        ("action_key",),
        ("operation_id",),
        ("operation_occurrence_id",),
    ),
    "planning_request_authority_bindings": (("request_id",),),
    "requirements_revisions": (("revision_id",),),
    "results": (("attempt_id", "turn_id"), ("result_id",)),
    "review_packages": (("package_id",),),
    "review_records": (("package_id",), ("record_id",)),
    "support_members": (("set_id", "member_kind", "member_id"),),
    "task_semantics": (("task_id", "binding_revision"),),
}
