# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0

"""TG-EXEC-2.0 immutable pins, input provenance and convergence side records.

SQL bytes are the reviewed 001_taskgraph_extension.sql, without parent fixtures.
Schema installation does not enable TaskGraph policy or runtime behavior.
"""

DDL = (
    "-- TG-EXEC-2.0, additive migration. Never execute on a live datab"
    "ase by hand.\n"
    "-- Register next UNUSED migration after H1H-ADM-1.0. Existing tab"
    "le names/keys are checked in preflight.\n"
    "-- Requires SQLite STRICT support, foreign_keys=ON. Transaction o"
    "wned by Store migration runner.\n"
    "CREATE TABLE taskgraph_policy_bindings (\n"
    " mission_id TEXT PRIMARY KEY NOT NULL REFERENCES missions(mission"
    "_id),\n"
    " kernel_version TEXT NOT NULL CHECK(kernel_version='taskgraph-exe"
    "c-v2'),\n"
    " policy_hash TEXT NOT NULL CHECK(length(policy_hash)=64),\n"
    " policy_json TEXT NOT NULL CHECK(json_valid(policy_json)),\n"
    " enabling_command_id TEXT NOT NULL UNIQUE,\n"
    " enabling_receipt_hash TEXT NOT NULL CHECK(length(enabling_receip"
    "t_hash)=64),\n"
    " created_at REAL NOT NULL\n"
    ") STRICT;\n"
    "\n"
    "-- Immutable replay source; existing plan_revisions remains the O"
    "NLY active pointer.\n"
    "-- network_json is canonical NetworkDocumentV1. Runtime states/pe"
    "rmissions are NOT copied into it.\n"
    "CREATE TABLE taskgraph_revision_records (\n"
    " mission_id TEXT NOT NULL REFERENCES taskgraph_policy_bindings(mi"
    "ssion_id),\n"
    " revision INTEGER NOT NULL CHECK(revision>=0),\n"
    " parent_revision INTEGER,\n"
    " parent_manifest_hash TEXT,\n"
    " source_kind TEXT NOT NULL CHECK(source_kind IN ('SEED_COMMIT','C"
    "OMMIT','CAPTURED_BASELINE')),\n"
    " requirements_revision INTEGER NOT NULL CHECK(requirements_revisi"
    "on>=0),\n"
    " manifest_hash TEXT NOT NULL CHECK(length(manifest_hash)=64),\n"
    " sdk_snapshot_hash TEXT NOT NULL CHECK(length(sdk_snapshot_hash)="
    "64),\n"
    " network_json TEXT NOT NULL CHECK(json_valid(network_json)),\n"
    " certificate_json TEXT NOT NULL CHECK(json_valid(certificate_json"
    ")),\n"
    " admission_check_id TEXT REFERENCES planning_admission_checks(che"
    "ck_id),\n"
    " event_id TEXT NOT NULL REFERENCES events(event_id),\n"
    " command_id TEXT NOT NULL,\n"
    " created_at REAL NOT NULL,\n"
    " PRIMARY KEY(mission_id,revision),\n"
    " UNIQUE(mission_id,revision,manifest_hash),\n"
    " UNIQUE(mission_id,command_id),\n"
    " FOREIGN KEY(mission_id,revision) REFERENCES plan_revisions(missi"
    "on_id,revision),\n"
    " FOREIGN KEY(mission_id,requirements_revision) REFERENCES require"
    "ments_revisions(mission_id,revision),\n"
    " FOREIGN KEY(mission_id,parent_revision,parent_manifest_hash)\n"
    "   REFERENCES taskgraph_revision_records(mission_id,revision,mani"
    "fest_hash),\n"
    " CHECK((source_kind='CAPTURED_BASELINE' AND admission_check_id IS"
    " NULL) OR\n"
    "       (source_kind IN ('SEED_COMMIT','COMMIT') AND admission_che"
    "ck_id IS NOT NULL)),\n"
    " CHECK((parent_revision IS NULL AND parent_manifest_hash IS NULL "
    "AND source_kind IN ('SEED_COMMIT','CAPTURED_BASELINE')) OR\n"
    "       (parent_revision IS NOT NULL AND parent_manifest_hash IS N"
    "OT NULL AND length(parent_manifest_hash)=64 AND revision=parent_r"
    "evision+1 AND source_kind='COMMIT'))\n"
    ") STRICT;\n"
    "\n"
    "CREATE TABLE taskgraph_member_pins (\n"
    " mission_id TEXT NOT NULL,\n"
    " revision INTEGER NOT NULL,\n"
    " occurrence_id TEXT NOT NULL,\n"
    " task_id TEXT NOT NULL,\n"
    " binding_revision INTEGER NOT NULL CHECK(binding_revision>=0),\n"
    " binding_hash TEXT NOT NULL CHECK(length(binding_hash)=64),\n"
    " PRIMARY KEY(mission_id,revision,occurrence_id),\n"
    " FOREIGN KEY(mission_id,revision) REFERENCES taskgraph_revision_r"
    "ecords(mission_id,revision),\n"
    " FOREIGN KEY(mission_id,revision,occurrence_id) REFERENCES plan_m"
    "emberships(mission_id,revision,occurrence_id),\n"
    " FOREIGN KEY(task_id,binding_revision) REFERENCES task_semantics("
    "task_id,binding_revision)\n"
    ") STRICT;\n"
    "CREATE INDEX taskgraph_member_pins_task_idx ON taskgraph_member_p"
    "ins(mission_id,task_id,revision);\n"
    "\n"
    "CREATE TABLE taskgraph_method_pins (\n"
    " mission_id TEXT NOT NULL,\n"
    " revision INTEGER NOT NULL,\n"
    " instance_id TEXT NOT NULL,\n"
    " goal_occurrence_id TEXT NOT NULL,\n"
    " adopted INTEGER NOT NULL CHECK(adopted IN (0,1)),\n"
    " draft_hash TEXT NOT NULL CHECK(length(draft_hash)=64),\n"
    " PRIMARY KEY(mission_id,revision,instance_id),\n"
    " FOREIGN KEY(mission_id,revision) REFERENCES taskgraph_revision_r"
    "ecords(mission_id,revision),\n"
    " FOREIGN KEY(mission_id,instance_id) REFERENCES method_instances("
    "mission_id,instance_id),\n"
    " FOREIGN KEY(mission_id,revision,goal_occurrence_id) REFERENCES p"
    "lan_memberships(mission_id,revision,occurrence_id)\n"
    ") STRICT;\n"
    "CREATE UNIQUE INDEX taskgraph_one_adopted_per_goal_idx\n"
    " ON taskgraph_method_pins(mission_id,revision,goal_occurrence_id)"
    " WHERE adopted=1;\n"
    "\n"
    "-- Derived demand index, not a second financial ledger. One row p"
    "er adopted slot.\n"
    "CREATE TABLE taskgraph_demand_refs (\n"
    " mission_id TEXT NOT NULL,\n"
    " revision INTEGER NOT NULL,\n"
    " consumer_instance_id TEXT NOT NULL,\n"
    " slot_key TEXT NOT NULL,\n"
    " slot_occurrence_id TEXT NOT NULL,\n"
    " producer_occurrence_id TEXT NOT NULL,\n"
    " obligation_id TEXT NOT NULL,\n"
    " mode TEXT NOT NULL CHECK(mode IN ('new_work','reuse_accepted','s"
    "hare_active')),\n"
    " requiredness TEXT NOT NULL CHECK(requiredness IN ('required','op"
    "tional_authorized','conditional')),\n"
    " source_slot_hash TEXT NOT NULL CHECK(length(source_slot_hash)=64"
    "),\n"
    " PRIMARY KEY(mission_id,revision,consumer_instance_id,slot_key),\n"
    " FOREIGN KEY(mission_id,revision,consumer_instance_id) REFERENCES"
    " taskgraph_method_pins(mission_id,revision,instance_id),\n"
    " FOREIGN KEY(consumer_instance_id,slot_key) REFERENCES method_chi"
    "ld_occurrences(instance_id,slot_key),\n"
    " FOREIGN KEY(mission_id,revision,slot_occurrence_id) REFERENCES p"
    "lan_memberships(mission_id,revision,occurrence_id),\n"
    " FOREIGN KEY(mission_id,revision,producer_occurrence_id) REFERENC"
    "ES plan_memberships(mission_id,revision,occurrence_id),\n"
    " FOREIGN KEY(mission_id,obligation_id) REFERENCES obligations(mis"
    "sion_id,obligation_id)\n"
    ") STRICT;\n"
    "CREATE INDEX taskgraph_demand_producer_idx ON taskgraph_demand_re"
    "fs(mission_id,revision,producer_occurrence_id);\n"
    "\n"
    "-- Existing input_manifest_bindings may collapse repeated attempt"
    "s with equal bytes;\n"
    "-- this is the exact per-attempt association, not another manifes"
    "t content store.\n"
    "CREATE TABLE taskgraph_attempt_inputs (\n"
    " attempt_id TEXT PRIMARY KEY NOT NULL REFERENCES attempts(attempt"
    "_id),\n"
    " mission_id TEXT NOT NULL,\n"
    " task_id TEXT NOT NULL,\n"
    " occurrence_id TEXT NOT NULL,\n"
    " source_revision INTEGER NOT NULL,\n"
    " binding_revision INTEGER NOT NULL,\n"
    " contract_hash TEXT NOT NULL CHECK(length(contract_hash)=64),\n"
    " input_binding_revision INTEGER NOT NULL CHECK(input_binding_revi"
    "sion>=0),\n"
    " dispatch_generation INTEGER NOT NULL CHECK(dispatch_generation>="
    "0),\n"
    " manifest_hash TEXT NOT NULL REFERENCES input_manifests(manifest_"
    "hash),\n"
    " intent_id TEXT NOT NULL UNIQUE REFERENCES dispatch_intents(inten"
    "t_id),\n"
    " creation_key TEXT NOT NULL UNIQUE,\n"
    " input_id TEXT NOT NULL,\n"
    " frozen_input_hash TEXT NOT NULL CHECK(length(frozen_input_hash)="
    "64),\n"
    " admission_check_id TEXT REFERENCES planning_admission_checks(che"
    "ck_id),\n"
    " origin_hash TEXT NOT NULL CHECK(length(origin_hash)=64),\n"
    " created_at REAL NOT NULL,\n"
    " FOREIGN KEY(mission_id,source_revision,occurrence_id) REFERENCES"
    " plan_memberships(mission_id,revision,occurrence_id),\n"
    " FOREIGN KEY(task_id,binding_revision) REFERENCES task_semantics("
    "task_id,binding_revision)\n"
    ") STRICT;\n"
    "CREATE INDEX taskgraph_attempt_inputs_occ_idx ON taskgraph_attemp"
    "t_inputs(mission_id,occurrence_id,dispatch_generation);\n"
    "\n"
    "-- Durable convergence coordination. It never records the externa"
    "l effect as resolved.\n"
    "CREATE TABLE taskgraph_convergence_jobs (\n"
    " job_id TEXT PRIMARY KEY NOT NULL,\n"
    " mission_id TEXT NOT NULL REFERENCES taskgraph_policy_bindings(mi"
    "ssion_id),\n"
    " decision_id TEXT NOT NULL REFERENCES planning_decisions(decision"
    "_id),\n"
    " request_id TEXT NOT NULL REFERENCES planning_requests(request_id"
    "),\n"
    " command_id TEXT NOT NULL,\n"
    " source_revision INTEGER NOT NULL,\n"
    " candidate_hash TEXT NOT NULL CHECK(length(candidate_hash)=64),\n"
    " impact_hash TEXT NOT NULL CHECK(length(impact_hash)=64),\n"
    " state TEXT NOT NULL CHECK(state IN ('FENCED','WAITING','READY','"
    "APPLIED','ABANDONED')),\n"
    " row_version INTEGER NOT NULL CHECK(row_version>=1),\n"
    " created_at REAL NOT NULL,\n"
    " updated_at REAL NOT NULL,\n"
    " UNIQUE(mission_id,decision_id),\n"
    " FOREIGN KEY(mission_id,source_revision) REFERENCES taskgraph_rev"
    "ision_records(mission_id,revision)\n"
    ") STRICT;\n"
    "CREATE TABLE taskgraph_convergence_targets (\n"
    " job_id TEXT NOT NULL REFERENCES taskgraph_convergence_jobs(job_i"
    "d),\n"
    " mission_id TEXT NOT NULL,\n"
    " source_revision INTEGER NOT NULL,\n"
    " occurrence_id TEXT NOT NULL,\n"
    " task_id TEXT NOT NULL,\n"
    " expected_generation INTEGER NOT NULL CHECK(expected_generation>="
    "0),\n"
    " target_kind TEXT NOT NULL CHECK(target_kind IN ('RETIRING','INPU"
    "T_REPLACED')),\n"
    " PRIMARY KEY(job_id,occurrence_id),\n"
    " FOREIGN KEY(mission_id,source_revision,occurrence_id) REFERENCES"
    " plan_memberships(mission_id,revision,occurrence_id)\n"
    ") STRICT;\n"
    "CREATE INDEX taskgraph_fence_lookup_idx ON taskgraph_convergence_"
    "targets(mission_id,task_id,job_id);\n"
    "\n"
    "-- Only graph follow-up notifications. Original dispatch_intents "
    "remains the work handoff authority.\n"
    "CREATE TABLE taskgraph_followups (\n"
    " message_id TEXT PRIMARY KEY NOT NULL,\n"
    " mission_id TEXT NOT NULL REFERENCES taskgraph_policy_bindings(mi"
    "ssion_id),\n"
    " source_event_id TEXT NOT NULL REFERENCES events(event_id),\n"
    " kind TEXT NOT NULL CHECK(kind IN ('REEVALUATE','CONVERGE','REQUE"
    "ST_COMPOSITION')),\n"
    " subject_key TEXT NOT NULL,\n"
    " dedupe_key TEXT NOT NULL UNIQUE,\n"
    " payload_hash TEXT NOT NULL CHECK(length(payload_hash)=64),\n"
    " payload_json TEXT NOT NULL CHECK(json_valid(payload_json)),\n"
    " delivery_state TEXT NOT NULL CHECK(delivery_state IN ('PENDING',"
    "'LEASED','ACKED','BLOCKED')),\n"
    " lease_owner TEXT,\n"
    " lease_until_ms INTEGER,\n"
    " attempts INTEGER NOT NULL CHECK(attempts>=0),\n"
    " row_version INTEGER NOT NULL CHECK(row_version>=1),\n"
    " next_attempt_ms INTEGER NOT NULL CHECK(next_attempt_ms>=0),\n"
    " last_error_code TEXT,\n"
    " consumer_receipt_json TEXT CHECK(consumer_receipt_json IS NULL O"
    "R json_valid(consumer_receipt_json)),\n"
    " CHECK((delivery_state='ACKED' AND consumer_receipt_json IS NOT N"
    "ULL) OR\n"
    "       (delivery_state<>'ACKED' AND consumer_receipt_json IS NULL"
    ")),\n"
    " CHECK((delivery_state='LEASED' AND lease_owner IS NOT NULL AND l"
    "ease_until_ms IS NOT NULL) OR\n"
    "       (delivery_state<>'LEASED' AND lease_owner IS NULL AND leas"
    "e_until_ms IS NULL))\n"
    ") STRICT;\n"
    "CREATE INDEX taskgraph_followups_poll_idx ON taskgraph_followups("
    "delivery_state,next_attempt_ms,mission_id);\n"
    "\n"
    "CREATE TRIGGER tg_revision_source_guard BEFORE INSERT ON taskgrap"
    "h_revision_records BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM events e WHERE e.event_id=NEW.event_id AND e.miss"
    "ion_id=NEW.mission_id\n"
    " ) THEN RAISE(ABORT,'TG_REVISION_EVENT_MISMATCH') END;\n"
    " SELECT CASE WHEN NEW.source_kind<>'CAPTURED_BASELINE' AND NOT EX"
    "ISTS (\n"
    "  SELECT 1 FROM planning_admission_checks c JOIN planning_request"
    "s r ON r.request_id=c.request_id\n"
    "  WHERE c.check_id=NEW.admission_check_id AND c.phase='APPLIED' A"
    "ND r.mission_id=NEW.mission_id\n"
    " ) THEN RAISE(ABORT,'TG_REVISION_ADMISSION_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_pin_subject_guard BEFORE INSERT ON taskgraph_me"
    "mber_pins BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM task_semantics s JOIN plan_memberships m\n"
    "    ON m.mission_id=NEW.mission_id AND m.revision=NEW.revision AN"
    "D m.occurrence_id=NEW.occurrence_id\n"
    "  WHERE s.task_id=NEW.task_id AND s.binding_revision=NEW.binding_"
    "revision\n"
    "    AND s.mission_id=NEW.mission_id AND m.task_id=s.task_id AND m"
    ".obligation_id=s.obligation_id\n"
    "    AND m.form=s.form AND s.content_hash=NEW.binding_hash\n"
    " ) THEN RAISE(ABORT,'TG_PIN_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_method_subject_guard BEFORE INSERT ON taskgraph"
    "_method_pins BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM method_instances i WHERE i.mission_id=NEW.mission"
    "_id AND i.instance_id=NEW.instance_id\n"
    "   AND i.goal_occurrence_id=NEW.goal_occurrence_id\n"
    " ) THEN RAISE(ABORT,'TG_METHOD_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_demand_subject_guard BEFORE INSERT ON taskgraph"
    "_demand_refs BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM taskgraph_method_pins p JOIN method_child_occurre"
    "nces c\n"
    "   ON c.instance_id=p.instance_id AND c.mission_id=p.mission_id\n"
    "  WHERE p.mission_id=NEW.mission_id AND p.revision=NEW.revision\n"
    "   AND p.instance_id=NEW.consumer_instance_id AND p.adopted=1 AND"
    " c.slot_key=NEW.slot_key\n"
    "   AND c.occurrence_id=NEW.slot_occurrence_id AND c.goal_occurren"
    "ce_id=NEW.producer_occurrence_id\n"
    "   AND c.obligation_id=NEW.obligation_id AND c.reuse_policy=NEW.m"
    "ode AND c.requiredness=NEW.requiredness\n"
    " ) THEN RAISE(ABORT,'TG_DEMAND_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_attempt_identity_guard BEFORE INSERT ON taskgra"
    "ph_attempt_inputs BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM attempts a JOIN dispatch_intents d ON d.subject_i"
    "d=a.attempt_id\n"
    "  JOIN plan_memberships m ON m.mission_id=a.mission_id AND m.task"
    "_id=a.task_id\n"
    "  JOIN task_semantics s ON s.task_id=a.task_id AND s.binding_revi"
    "sion=NEW.binding_revision\n"
    "  JOIN taskgraph_revision_records rr ON rr.mission_id=NEW.mission"
    "_id AND rr.revision=NEW.source_revision\n"
    "  LEFT JOIN planning_admission_checks c ON c.check_id=NEW.admissi"
    "on_check_id\n"
    "  LEFT JOIN planning_requests r ON r.request_id=c.request_id\n"
    "  JOIN input_manifest_bindings b ON b.mission_id=a.mission_id AND"
    " b.task_id=a.task_id\n"
    "   AND b.manifest_hash=NEW.manifest_hash AND b.input_binding_revi"
    "sion=NEW.input_binding_revision\n"
    "  WHERE a.attempt_id=NEW.attempt_id AND a.mission_id=NEW.mission_"
    "id AND a.task_id=NEW.task_id\n"
    "   AND d.intent_id=NEW.intent_id AND d.mission_id=NEW.mission_id\n"
    "   AND d.creation_key=NEW.creation_key AND d.input_id=NEW.input_i"
    "d AND d.input_hash=NEW.frozen_input_hash\n"
    "   AND m.revision=NEW.source_revision AND m.occurrence_id=NEW.occ"
    "urrence_id AND m.form='primitive'\n"
    "   AND s.mission_id=NEW.mission_id AND s.form='primitive'\n"
    "   AND s.input_binding_revision=NEW.input_binding_revision AND s."
    "dispatch_generation=NEW.dispatch_generation\n"
    "   AND ((rr.source_kind='CAPTURED_BASELINE' AND rr.admission_chec"
    "k_id IS NULL AND NEW.admission_check_id IS NULL)\n"
    "     OR (rr.source_kind<>'CAPTURED_BASELINE' AND rr.admission_che"
    "ck_id=NEW.admission_check_id\n"
    "         AND r.mission_id=NEW.mission_id AND c.phase='APPLIED'))\n"
    " ) THEN RAISE(ABORT,'TG_ATTEMPT_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_convergence_identity_guard BEFORE INSERT ON tas"
    "kgraph_convergence_jobs BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM planning_requests r JOIN planning_decisions d ON "
    "d.request_id=r.request_id\n"
    "  WHERE r.request_id=NEW.request_id AND d.decision_id=NEW.decisio"
    "n_id AND r.mission_id=NEW.mission_id\n"
    " ) THEN RAISE(ABORT,'TG_CONVERGENCE_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_target_identity_guard BEFORE INSERT ON taskgrap"
    "h_convergence_targets BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM taskgraph_convergence_jobs j JOIN plan_membership"
    "s m\n"
    "   ON m.mission_id=j.mission_id AND m.revision=j.source_revision\n"
    "  WHERE j.job_id=NEW.job_id AND j.mission_id=NEW.mission_id AND j"
    ".source_revision=NEW.source_revision\n"
    "   AND m.occurrence_id=NEW.occurrence_id AND m.task_id=NEW.task_i"
    "d\n"
    " ) THEN RAISE(ABORT,'TG_TARGET_IDENTITY_MISMATCH') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_followup_owner_guard BEFORE INSERT ON taskgraph"
    "_followups BEGIN\n"
    " SELECT CASE WHEN NOT EXISTS (\n"
    "  SELECT 1 FROM events e WHERE e.event_id=NEW.source_event_id AND"
    " e.mission_id=NEW.mission_id\n"
    " ) THEN RAISE(ABORT,'TG_FOLLOWUP_OWNER_MISMATCH') END;\n"
    "END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_policy_bindings_no_update BEFORE UPDATE "
    "ON taskgraph_policy_bindings BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_policy_bindings_no_delete BEFORE DELETE "
    "ON taskgraph_policy_bindings BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_revision_records_no_update BEFORE UPDATE"
    " ON taskgraph_revision_records BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_revision_records_no_delete BEFORE DELETE"
    " ON taskgraph_revision_records BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_member_pins_no_update BEFORE UPDATE ON t"
    "askgraph_member_pins BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_member_pins_no_delete BEFORE DELETE ON t"
    "askgraph_member_pins BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_method_pins_no_update BEFORE UPDATE ON t"
    "askgraph_method_pins BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_method_pins_no_delete BEFORE DELETE ON t"
    "askgraph_method_pins BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_demand_refs_no_update BEFORE UPDATE ON t"
    "askgraph_demand_refs BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_demand_refs_no_delete BEFORE DELETE ON t"
    "askgraph_demand_refs BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_attempt_inputs_no_update BEFORE UPDATE O"
    "N taskgraph_attempt_inputs BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_attempt_inputs_no_delete BEFORE DELETE O"
    "N taskgraph_attempt_inputs BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "CREATE TRIGGER taskgraph_convergence_targets_no_update BEFORE UPD"
    "ATE ON taskgraph_convergence_targets BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER taskgraph_convergence_targets_no_delete BEFORE DEL"
    "ETE ON taskgraph_convergence_targets BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "\n"
    "-- These constrain permitted database transitions, but DO NOT rep"
    "lace real convergence/receipt checks.\n"
    "CREATE TRIGGER tg_convergence_transition BEFORE UPDATE ON taskgra"
    "ph_convergence_jobs BEGIN\n"
    " SELECT CASE WHEN NEW.job_id<>OLD.job_id OR NEW.mission_id<>OLD.m"
    "ission_id\n"
    "  OR NEW.decision_id<>OLD.decision_id OR NEW.request_id<>OLD.requ"
    "est_id\n"
    "  OR NEW.command_id<>OLD.command_id OR NEW.source_revision<>OLD.s"
    "ource_revision\n"
    "  OR NEW.candidate_hash<>OLD.candidate_hash OR NEW.impact_hash<>O"
    "LD.impact_hash\n"
    "  OR NEW.row_version<>OLD.row_version+1\n"
    "  THEN RAISE(ABORT,'TG_CONVERGENCE_IDENTITY_OR_VERSION') END;\n"
    " SELECT CASE WHEN NOT (\n"
    "   (OLD.state='FENCED' AND NEW.state IN ('WAITING','READY','ABAND"
    "ONED')) OR\n"
    "   (OLD.state='WAITING' AND NEW.state IN ('WAITING','READY','ABAN"
    "DONED')) OR\n"
    "   (OLD.state='READY' AND NEW.state IN ('WAITING','APPLIED','ABAN"
    "DONED'))\n"
    " ) THEN RAISE(ABORT,'TG_CONVERGENCE_TRANSITION') END;\n"
    "END;\n"
    "CREATE TRIGGER tg_convergence_no_delete BEFORE DELETE ON taskgrap"
    "h_convergence_jobs BEGIN\n"
    " SELECT RAISE(ABORT,'TG_IMMUTABLE'); END;\n"
    "CREATE TRIGGER tg_followup_transition BEFORE UPDATE ON taskgraph_"
    "followups BEGIN\n"
    " SELECT CASE WHEN NEW.message_id<>OLD.message_id OR NEW.mission_i"
    "d<>OLD.mission_id\n"
    "  OR NEW.source_event_id<>OLD.source_event_id OR NEW.kind<>OLD.ki"
    "nd\n"
    "  OR NEW.subject_key<>OLD.subject_key OR NEW.dedupe_key<>OLD.dedu"
    "pe_key\n"
    "  OR NEW.payload_hash<>OLD.payload_hash OR NEW.payload_json<>OLD."
    "payload_json\n"
    "  OR NEW.row_version<>OLD.row_version+1\n"
    "  THEN RAISE(ABORT,'TG_FOLLOWUP_IDENTITY_OR_VERSION') END;\n"
    " SELECT CASE WHEN NOT (\n"
    "   (OLD.delivery_state='PENDING' AND NEW.delivery_state='LEASED')"
    " OR\n"
    "   (OLD.delivery_state='LEASED' AND NEW.delivery_state IN ('PENDI"
    "NG','LEASED','ACKED','BLOCKED')) OR\n"
    "   (OLD.delivery_state='BLOCKED' AND NEW.delivery_state='PENDING'"
    ")\n"
    " ) THEN RAISE(ABORT,'TG_FOLLOWUP_TRANSITION') END;\n"
    "END;\n"
)
