"""Storage-facing protocols for the product-neutral execution control plane."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, Sequence, TypeAlias, runtime_checkable
from .contracts import ActorAction, ActorContext, ChildCommandIntent, ChildCommandRecord, ChildSignalRecord, CreateRunResult, DecisionAuthorization, DecisionOpen, DecisionRecord, DecisionSignal, DeliveryRecord, DeliverySpec, FinalizeRunResult, GrantConsume, LegacyRunProjection, RunCreate, RunEvent, RunEventCandidate, RunLinkSpec, RunRecord, RunRef, RunStatus, WorkflowRunSeed
from .evidence import EvidenceContext, EvidenceSelection
RunView = RunRecord | LegacyRunProjection
SinkKey: TypeAlias = tuple[str, str]

@runtime_checkable
class ExecutionUnitOfWork(Protocol):
    """The single durable boundary for run, decision, event and child state."""

    async def create(self, spec: RunCreate, *, initial_event: RunEventCandidate | None=None) -> CreateRunResult:
        ...

    async def finalize_and_enqueue_delivery(self, run_id: str, *, expected_version: int, terminal_status: RunStatus, event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> FinalizeRunResult:
        ...

    async def request_cancel(self, run_id: str, *, expected_version: int, reason: str, event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=()) -> RunRecord:
        ...

    async def query(self, ref: RunRef, actor: ActorContext) -> RunView:
        ...

    async def authorize(self, ref: RunRef, actor: ActorContext, action: ActorAction | str) -> RunView:
        ...

    async def list_child_links(self, ref: RunRef, actor: ActorContext) -> tuple[RunLinkSpec, ...]:
        ...

    async def list_recoverable(self, *, limit: int=10000) -> tuple[RunRecord, ...]:
        ...

    async def claim_recovery(self, run_id: str, *, owner: str, lease_seconds: float=30.0) -> Any:
        ...

    async def claim_workflow_recovery_handoff(self, recovery_lease: Any, *, workflow_owner: str, ttl_seconds: float=90.0) -> Any:
        ...

    async def renew_recovery(self, lease: Any, *, lease_seconds: float=30.0) -> Any:
        ...

    async def assert_recovery_fence(self, lease: Any) -> None:
        ...

    async def release_recovery(self, lease: Any) -> bool:
        ...

    async def get_event(self, event_id: str) -> RunEvent:
        ...

    async def list_events(self, run_id: str, *, after_durable_seq: int=0) -> tuple[RunEvent, ...]:
        ...

    async def list_event_deliveries(self, event_id: str) -> tuple[DeliveryRecord, ...]:
        ...

    async def claim_delivery(self, *, owner_generation: int, sink_keys: Sequence[SinkKey]=(), claim_ttl_seconds: float=30.0) -> DeliveryRecord | None:
        ...

    async def complete_delivery(self, delivery_id: str, *, expected_version: int, owner_generation: int) -> DeliveryRecord:
        ...

    async def release_delivery(self, delivery_id: str, *, expected_version: int, owner_generation: int, error: str, retry_at: float | None, discard: bool) -> DeliveryRecord:
        ...

    async def open_decision(self, request: DecisionOpen, actor: ActorContext, *, expected_run_version: int) -> DecisionRecord:
        ...

    async def get_decision(self, decision_id: str, *, ref: RunRef, actor: ActorContext) -> DecisionRecord:
        ...

    async def resolve_decision(self, signal: DecisionSignal, actor: ActorContext) -> tuple[DecisionRecord, DecisionAuthorization | None]:
        ...

    async def resolve_decision_and_advance_boundary(self, signal: DecisionSignal, actor: ActorContext, *, expected_continuation_version: int, continuation_payload: Mapping[str, Any], resumed_event: RunEventCandidate, next_decision: DecisionOpen | None=None, deliveries: Sequence[DeliverySpec]=()) -> tuple[DecisionRecord, DecisionAuthorization | None, Any, RunEvent]:
        ...

    async def cancel_open_decisions(self, ref: RunRef, actor: ActorContext, *, expected_run_version: int) -> tuple[DecisionRecord, ...]:
        ...

    async def consume_authorization(self, request: GrantConsume, actor: ActorContext) -> DecisionAuthorization:
        ...

    async def consume_grant_and_claim_effect(self, request: GrantConsume, actor: ActorContext, *, effect_type: str, policy: Mapping[str, Any], prepared: Mapping[str, Any], worker_owner: str, worker_epoch: int, recovery_lease: Any | None=None) -> Any:
        ...

    async def settle_effect_and_advance_boundary(self, effect_id: str, **kwargs: Any) -> Any:
        ...

    async def mark_effect_unknown(self, effect_id: str, **kwargs: Any) -> None:
        ...

    async def read_effect_outcome(self, *, run_id: str, call_id: str, effect_id: str, args_hash: str, capability_hash: str, scope_hash: str) -> tuple[str, Mapping[str, Any], str | None, tuple[str, ...]] | None:
        ...

    async def initialize(self) -> None:
        ...

    async def get_execution_owner(self, run_id: str) -> tuple[str, int] | None:
        ...

    async def save_continuation(self, run_id: str, expected_version: int, payload: Mapping[str, Any], decision: DecisionOpen | None=None, *, recovery_lease: Any | None=None) -> Any:
        ...

    async def load_continuation(self, run_id: str) -> Any | None:
        ...

    async def lookup_completion_evidence(self, context: EvidenceContext) -> EvidenceSelection:
        ...

    async def promote_and_persist_batch_boundary(self, spec: RunCreate, *, expected_run_version: int, expected_continuation_version: int, payload: Mapping[str, Any], decision: DecisionOpen | None=None, waiting_event: RunEventCandidate | None=None, deliveries: Sequence[DeliverySpec]=()) -> tuple[CreateRunResult, Any]:
        ...

    async def append_event(self, run_id: str, *, expected_version: int, event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> RunEvent:
        ...

    async def start_workflow(self, spec: RunCreate, workflow: WorkflowRunSeed, *, association_event: RunEventCandidate | None=None, accepted_event: RunEventCandidate | None=None, deliveries: Sequence[DeliverySpec]=()) -> CreateRunResult:
        ...

    async def commit_child_command(self, intent: ChildCommandIntent, *, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def get_child_command(self, operation_id: str) -> ChildCommandRecord | None:
        ...

    async def get_child_command_for_run(self, child_run_id: str) -> ChildCommandRecord | None:
        ...

    async def lease_child_commands(self, *, owner: str, limit: int, lease_seconds: float, parent_run_id: str | None=None, recovery_lease: Any | None=None) -> tuple[ChildCommandRecord, ...]:
        ...

    async def schedule_child_command(self, operation_id: str, *, lease_owner: str, lease_epoch: int, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def acknowledge_child_command(self, operation_id: str, *, lease_owner: str, lease_epoch: int, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def finalize_child_and_enqueue_parent_signal(self, operation_id: str, *, expected_version: int, terminal_status: RunStatus, event: RunEventCandidate, value: object=None, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> FinalizeRunResult:
        ...

    async def list_pending_child_signals(self, parent_run_id: str, *, recovery_lease: Any | None=None) -> tuple[ChildSignalRecord, ...]:
        ...

    async def list_pending_child_signal_parents(self, *, limit: int=10000) -> tuple[RunRecord, ...]:
        ...

    async def discard_terminal_detached_child_signal(self, signal_id: str) -> ChildSignalRecord:
        ...

    async def prepare_workflow_child_resume(self, signal_id: str, *, recovery_lease: Any) -> DecisionRecord:
        ...

    async def apply_child_signal_and_ack(self, signal_id: str, *, expected_continuation_version: int, continuation_payload: Mapping[str, Any], event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> tuple[ChildSignalRecord, Any, RunEvent]:
        ...
__all__ = ['ExecutionUnitOfWork', 'RunView', 'SinkKey']
