"""Storage-facing protocols for the product-neutral execution control plane."""
from __future__ import annotations
from typing import Any, Mapping, Protocol, Sequence, TypeAlias, runtime_checkable
from .contracts import ActorAction, ActorContext, ChildCommandIntent, ChildCommandRecord, ChildSignalRecord, CreateRunResult, DecisionAuthorization, DecisionOpen, DecisionRecord, DecisionSignal, DeliveryRecord, DeliverySpec, FinalizeRunResult, GrantConsume, LegacyRunProjection, RunCreate, RunEvent, RunEventCandidate, RunLinkSpec, RunRecord, RunRef, RunStatus, WorkflowRunSeed
from .evidence import EvidenceContext, EvidenceSelection
RunView = RunRecord | LegacyRunProjection
SinkKey: TypeAlias = tuple[str, str]

@runtime_checkable
class ExecutionUnitOfWork(Protocol):
    """The single durable boundary for run, decision, event and child state."""

    async def create(self, spec: RunCreate, *, initial_event: RunEventCandidate | None=None) -> CreateRunResult:
        ...

    async def commit_run_outcome(self, run_id: str, *, expected_version: int, terminal_status: RunStatus | None=None, event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None, cancel_reason: str | None=None) -> FinalizeRunResult | RunRecord:
        ...

    async def query(self, ref: RunRef, actor: ActorContext) -> RunView:
        ...

    async def authorize(self, ref: RunRef, actor: ActorContext, action: ActorAction | str) -> RunView:
        ...

    async def list_child_links(self, ref: RunRef, actor: ActorContext) -> tuple[RunLinkSpec, ...]:
        ...

    async def list_recoverable(self, *, limit: int=10000) -> tuple[RunRecord, ...]:
        ...

    async def recovery_scope(self, subject: str | Any, *, owner: str | None=None, lease_seconds: float | None=30.0) -> Any:
        ...

    async def claim_workflow_recovery_handoff(self, recovery_lease: Any, *, workflow_owner: str, ttl_seconds: float=90.0) -> Any:
        ...

    async def assert_recovery_fence(self, lease: Any) -> None:
        ...

    async def get_event(self, event_id: str) -> RunEvent:
        ...

    async def list_events(self, run_id: str, *, after_durable_seq: int=0) -> tuple[RunEvent, ...]:
        ...

    async def list_event_deliveries(self, event_id: str) -> tuple[DeliveryRecord, ...]:
        ...

    async def claim_delivery(self, *, owner_generation: int, sink_keys: Sequence[SinkKey]=(), claim_ttl_seconds: float=30.0) -> DeliveryRecord | None:
        ...

    async def settle_delivery(self, delivery_id: str, *, expected_version: int, owner_generation: int, error: str | None=None, retry_at: float | None=None, discard: bool=False) -> DeliveryRecord:
        ...

    async def get_decision(self, decision_id: str, *, ref: RunRef, actor: ActorContext) -> DecisionRecord:
        ...

    async def commit_decision(self, signal: DecisionOpen | DecisionSignal, actor: ActorContext, *, expected_run_version: int | None=None, expected_continuation_version: int | None=None, continuation_payload: Mapping[str, Any] | None=None, resumed_event: RunEventCandidate | None=None, next_decision: DecisionOpen | None=None, deliveries: Sequence[DeliverySpec]=()) -> tuple[DecisionRecord, DecisionAuthorization | None] | tuple[DecisionRecord, DecisionAuthorization | None, Any, RunEvent]:
        ...

    async def cancel_open_decisions(self, ref: RunRef, actor: ActorContext, *, expected_run_version: int) -> tuple[DecisionRecord, ...]:
        ...

    async def claim_tool_call(self, request: GrantConsume | None, actor: ActorContext, **kwargs: Any) -> DecisionAuthorization | Any:
        ...

    async def settle_effect(self, effect_id: str, **kwargs: Any) -> Any:
        ...

    async def read_effect_outcome(self, *, run_id: str, call_id: str, effect_id: str, args_hash: str, capability_hash: str, scope_hash: str) -> tuple[str, Mapping[str, Any], str | None, tuple[str, ...]] | None:
        ...

    async def initialize(self) -> None:
        ...

    async def get_execution_owner(self, run_id: str) -> tuple[str, int] | None:
        ...

    async def persist_react_boundary(self, run: str | RunCreate, expected_continuation_version: int, payload: Mapping[str, Any], decision: DecisionOpen | None=None, **kwargs: Any) -> Any:
        ...

    async def load_continuation(self, run_id: str) -> Any | None:
        ...

    async def lookup_completion_evidence(self, context: EvidenceContext) -> EvidenceSelection:
        ...

    async def append_event(self, run_id: str, *, expected_version: int, event: RunEventCandidate, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> RunEvent:
        ...

    async def start_workflow(self, spec: RunCreate, workflow: WorkflowRunSeed, *, association_event: RunEventCandidate | None=None, accepted_event: RunEventCandidate | None=None, deliveries: Sequence[DeliverySpec]=()) -> CreateRunResult:
        ...

    async def commit_child_command(self, intent: ChildCommandIntent, *, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def get_child_command(self, operation_id: str) -> ChildCommandRecord | None:
        ...

    async def get_child_command_for_run(self, child_run_id: str) -> ChildCommandRecord | None:
        ...

    async def lease_child_commands(self, *, owner: str, limit: int, lease_seconds: float, parent_run_id: str | None=None, recovery_lease: Any | None=None) -> tuple[ChildCommandRecord, ...]:
        ...

    async def schedule_child_command(self, operation_id: str, *, lease_owner: str, lease_epoch: int, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def acknowledge_child_command(self, operation_id: str, *, lease_owner: str, lease_epoch: int, recovery_lease: Any | None=None) -> ChildCommandRecord:
        ...

    async def finalize_child_and_enqueue_parent_signal(self, operation_id: str, *, expected_version: int, terminal_status: RunStatus, event: RunEventCandidate, value: object=None, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> FinalizeRunResult:
        ...

    async def list_pending_child_signals(self, parent_run_id: str, *, recovery_lease: Any | None=None) -> tuple[ChildSignalRecord, ...]:
        ...

    async def list_pending_child_signal_parents(self, *, limit: int=10000) -> tuple[RunRecord, ...]:
        ...

    async def prepare_workflow_child_resume(self, signal_id: str, *, recovery_lease: Any) -> DecisionRecord:
        ...

    async def ack_child_signal(self, signal_id: str, *, expected_continuation_version: int | None=None, continuation_payload: Mapping[str, Any] | None=None, event: RunEventCandidate | None=None, deliveries: Sequence[DeliverySpec]=(), recovery_lease: Any | None=None) -> ChildSignalRecord | tuple[ChildSignalRecord, Any, RunEvent]:
        ...
__all__ = ['ExecutionUnitOfWork', 'RunView', 'SinkKey']
