import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { PrimaryTaskPanel } from "./PrimaryTaskPanel";
import { PrimaryMemoryPanel } from "./PrimaryMemoryPanel";
import { wire } from "../primary/testing/graphFixture";
import { boundOpen, evidenceView, groups, listPage, open, page, planView, search } from "../primary/testing/taskScopeFixture";
vi.mock("./MemoryGraphCanvas", () => ({ memoryTypeLabels: {}, MemoryGraphCanvas: () => <div /> }));
afterEach(cleanup);

const searchFor = (text: string) => {
  fireEvent.change(screen.getByRole("textbox", { name: "搜索任务" }), { target: { value: text } });
  fireEvent.click(screen.getByRole("button", { name: "搜索" }));
};
it("shows candidates without archive content, then reveals views only after exact open and on-demand page-in", async () => {
  const w = wire(); render(<PrimaryTaskPanel port={w.port} primaryRef="p" verifiedOwnerKey="owner:1" ready />);
  expect(w.sent).toHaveLength(0);
  searchFor("照片");
  expect(w.sent).toHaveLength(1); expect(w.sent[0].operation).toBe("task_scope.search");
  await act(async () => w.reply(0, search));
  expect(screen.getByText("整理照片库")).toBeTruthy(); expect(screen.getByText("整理视频库")).toBeTruthy();
  expect(screen.getByText(/候选 2 项（不授予任何权限）/)).toBeTruthy();
  expect(screen.queryByText(/归档秘密计划|下一步：导入 3 月/)).toBeNull();
  expect(screen.queryByRole("article", { name: "任务详情" })).toBeNull();
  expect(screen.getAllByText(/^scope-a/).length).toBe(1);
  fireEvent.click(screen.getAllByRole("button", { name: "精确打开" })[0]);
  expect(w.sent[1].operation).toBe("task_scope.open_exact");
  expect(w.sent[1].request).toEqual({ scope_ref: "scope-a", expected_source_hash: "a".repeat(64) });
  await act(async () => w.reply(1, open));
  expect(screen.getByRole("article", { name: "任务详情" })).toBeTruthy();
  expect(screen.getByText(/# 整理照片库/)).toBeTruthy();
  expect(screen.getByText(/事件水位：12 · 检查点序号：2/)).toBeTruthy();
  expect(screen.getByText(/未附带实时漂移探测/)).toBeTruthy();
  expect(screen.getByText(/绑定修订 1/)).toBeTruthy();
  expect(screen.queryByRole("switch")).toBeNull();
  expect(screen.queryByRole("button", { name: /继续|绑定|修改|Auto|Manual/ })).toBeNull();
  expect(screen.queryByText(/归档秘密计划|完整计划正文/)).toBeNull();
  expect(w.sent).toHaveLength(2);
  fireEvent.click(screen.getByRole("button", { name: "读取 PLAN" }));
  expect(w.sent[2].operation).toBe("task_scope.view"); expect(w.sent[2].request).toEqual({ scope_ref: "scope-a", kind: "PLAN" });
  await act(async () => w.reply(2, planView));
  expect(screen.getByText(/完整计划正文/)).toBeTruthy();
  fireEvent.click(screen.getByRole("button", { name: "读取 EVIDENCE" }));
  await act(async () => w.reply(3, evidenceView));
  fireEvent.click(screen.getByRole("button", { name: "列出证据分组" }));
  expect(w.sent[4].operation).toBe("task_scope.evidence_groups");
  expect(w.sent[4].request).toEqual({ scope_ref: "scope-a", source_ref: "source-a", source_hash: "a".repeat(64), limit: 8 });
  await act(async () => w.reply(4, groups));
  fireEvent.click(screen.getByRole("button", { name: "读取分组 1" }));
  expect(w.sent[5].operation).toBe("task_scope.evidence_page");
  expect(w.sent[5].request).toMatchObject({ group_ref: "group-1", group_hash: "3".repeat(64) });
  await act(async () => w.reply(5, page));
  expect(screen.getByText(/证据事件正文/)).toBeTruthy();
  expect(w.sent.every((r) => r.operation.startsWith("task_scope.") && !/mutate|create|binding|enqueue/.test(r.operation))).toBe(true);
});
it("clears candidates and views immediately on identity loss, change events and owner rebind", async () => {
  const w = wire(); const ui = render(<PrimaryTaskPanel port={w.port} primaryRef="p" verifiedOwnerKey="owner:1" ready />);
  searchFor("照片"); await act(async () => w.reply(0, search));
  fireEvent.click(screen.getAllByRole("button", { name: "精确打开" })[0]); await act(async () => w.reply(1, open));
  fireEvent.click(screen.getByRole("button", { name: "读取 PLAN" }));
  await act(async () => w.emit({ type: "human_memory_changed", payload: {} }));
  expect(screen.queryByText("整理照片库")).toBeNull(); expect(screen.queryByRole("article")).toBeNull();
  expect(screen.getByText(/已失效，请重新搜索/)).toBeTruthy();
  await act(async () => w.reply(2, planView));
  expect(screen.queryByText(/完整计划正文/)).toBeNull();
  searchFor("照片"); await act(async () => w.reply(3, search));
  expect(screen.getByText("整理照片库")).toBeTruthy();
  await act(async () => w.emit({ type: "companion_profile_bound", payload: { profile_id: "other", profile_generation: 2 } }));
  expect(screen.queryByText("整理照片库")).toBeNull(); expect(screen.getByText("等待当前连接身份确认")).toBeTruthy();
  ui.rerender(<PrimaryTaskPanel port={w.port} primaryRef="p" verifiedOwnerKey={null} ready={false} />);
  expect(screen.getByText("等待当前连接身份确认")).toBeTruthy(); expect(screen.queryByRole("textbox")).toBeNull();
});
it("rejects a reply with missing fields and never shows partial data", async () => {
  const w = wire(); render(<PrimaryTaskPanel port={w.port} primaryRef="p" verifiedOwnerKey="owner:1" ready />);
  searchFor("照片");
  await act(async () => w.reply(0, { candidates: [{ ...search.candidates[0], source_hash: undefined }], next_cursor: null, receipt_hash: "b".repeat(64) }));
  expect(screen.queryByText("整理照片库")).toBeNull(); expect(screen.getByRole("alert").textContent).toMatch(/未通过核对/);
  searchFor("照片"); await act(async () => w.reply(1, search));
  fireEvent.click(screen.getAllByRole("button", { name: "精确打开" })[0]);
  await act(async () => w.reply(2, { ...open, drift_report: undefined }));
  expect(screen.queryByRole("article")).toBeNull(); expect(screen.getByRole("alert").textContent).toMatch(/未通过核对/);
  fireEvent.click(screen.getAllByRole("button", { name: "精确打开" })[0]);
  await act(async () => w.reply(3, open));
  fireEvent.click(screen.getByRole("button", { name: "读取 PLAN" }));
  await act(async () => w.reply(4, { ...planView, content: undefined }));
  expect(screen.queryByText(/完整计划正文/)).toBeNull(); expect(screen.getByRole("alert").textContent).toMatch(/未通过核对/);
  expect(screen.getByRole("article", { name: "任务详情" })).toBeTruthy();
  // 审查 F-1：另一 source revision 的视图是"过期"而非畸形——已打开快照必须退出。
  fireEvent.click(screen.getByRole("button", { name: "读取 PLAN" }));
  await act(async () => w.reply(5, { ...planView, source_hash: "9".repeat(64) }));
  expect(screen.queryByText(/完整计划正文/)).toBeNull(); expect(screen.getByRole("alert").textContent).toMatch(/过期/);
  expect(screen.queryByRole("article", { name: "任务详情" })).toBeNull();
});
it("memory panel exposes the task tab beside list, graph and audit", () => {
  const w = wire(); render(<PrimaryMemoryPanel port={w.port} primaryRef="p" verifiedOwnerKey="owner:1" ready />);
  fireEvent.click(screen.getByRole("button", { name: "任务" }));
  expect(screen.getByRole("region", { name: "任务范围" })).toBeTruthy();
  expect(screen.getByRole("textbox", { name: "搜索任务" })).toBeTruthy();
  expect(w.sent.filter((r) => r.operation.startsWith("task_scope."))).toHaveLength(0);
});
it("recent list is explicit, shows Host binding facts read-only, and opens items exactly", async () => {
  const w = wire(); render(<PrimaryTaskPanel port={w.port} primaryRef="p" verifiedOwnerKey="owner:1" ready />);
  expect(w.sent).toHaveLength(0);
  fireEvent.click(screen.getByRole("button", { name: "最近任务" }));
  expect(w.sent[0].operation).toBe("task_scope.list"); expect(w.sent[0].request).toEqual({ limit: 20 });
  await act(async () => w.reply(0, listPage));
  expect(screen.getByText(/最近任务 2 项/)).toBeTruthy();
  const items = screen.getByRole("list", { name: "最近任务" });
  expect(items.textContent).toMatch(/整理照片库.*整理视频库/s);
  expect(items.textContent).toMatch(/\/Users\/me\/photos（Auto（自动），根目录仍在）/);
  expect(items.textContent).toMatch(/尚无工作区绑定/);
  expect(screen.queryByText(/归档秘密计划|下一步：导入 3 月/)).toBeNull();
  expect(screen.queryByRole("article", { name: "任务详情" })).toBeNull();
  expect(screen.queryByRole("switch")).toBeNull();
  expect(screen.queryByRole("button", { name: /继续|绑定|修改|Auto|Manual/ })).toBeNull();
  fireEvent.click(screen.getAllByRole("button", { name: "精确打开" })[0]);
  expect(w.sent[1].operation).toBe("task_scope.open_exact");
  expect(w.sent[1].request).toEqual({ scope_ref: "scope-a", expected_source_hash: "a".repeat(64) });
  await act(async () => w.reply(1, boundOpen));
  const article = screen.getByRole("article", { name: "任务详情" });
  expect(article.textContent).toMatch(/Host 记录模式 Auto（自动），根目录仍在。根：\/Users\/me\/photos/);
  expect(article.textContent).toMatch(/Host 未提供：host_unavailable/);
  expect(screen.queryByRole("button", { name: /继续|绑定|修改|Auto|Manual/ })).toBeNull();
  expect(w.sent.every((r) => r.operation.startsWith("task_scope.") && !/mutate|create|binding|enqueue/.test(r.operation))).toBe(true);
});
