# SPDX-FileCopyrightText: 2026 DennyWanye
# SPDX-License-Identifier: Apache-2.0

"""Public Tool, authorization, and reconciliation contracts."""

from .authorization import (
    AuthorizationDecision,
    AuthorizationPort,
    AuthorizationReceipt,
    AuthorizationRequest,
    AuthorizationResult,
    PreparedToolEffect,
    bind_authorization_receipts,
    sdk_authorization_receipt,
)
from .contracts import (
    CancellationToken,
    FunctionTool,
    JsonObject,
    Tool,
    ToolCall,
    ToolContext,
    ToolHandler,
    ToolOutcome,
    ToolResult,
    ToolSpec,
)
from .errors import (
    DuplicateToolCallError,
    DuplicateToolError,
    LateToolResultError,
    MalformedToolArgumentsError,
    ToolRegistryError,
    UnknownToolError,
)
from .executor import EffectExecution, EffectExecutor, ToolAuthorizationPending
from .reconciliation import (
    ReconciliationObservation,
    ReconciliationState,
    ToolReconciliationPort,
)
from .registry import ToolCallState, ToolRegistry
from .runtime_catalog import (
    CatalogRunToolExposure,
    ExecutableToolRecord,
    RuntimeCapabilityKind,
    RuntimeCapabilityRecord,
    RuntimeToolCatalog,
    RuntimeToolCatalogError,
    RuntimeToolCatalogSnapshot,
    RuntimeToolDescription,
    RuntimeToolDescriptor,
    RuntimeToolSearchPage,
    RunToolExposurePort,
    RunToolExposureState,
    SkillResourceRecord,
    ToolActivationReceipt,
    ToolEffectClass,
    ToolExecutionPolicy,
    ToolExposureMode,
    ToolRouteRequirement,
    ToolTaskScopeRequirement,
    WorkflowProfileRecord,
)
from .schema import (
    PUBLIC_PROGRESS_ARGUMENT,
    ArgumentsValidationError,
    SchemaDefinitionError,
    normalize_public_progress_arguments,
)
from .sidecar import (
    EffectKind,
    EffectPolicy,
    FunctionOutcomeParser,
    OutcomeParserPort,
    ResourceScopeResolverPort,
    Sidecar,
    ToolCompletionSemantics,
    ToolDispatchKind,
    ToolInventoryRecord,
    ToolOutcomeParser,
    ToolResource,
    ToolSidecar,
    builtin_outcome_parser,
    inventory_digest,
    parse_tool_outcome,
    resource_digest,
)

__all__ = (
    "ArgumentsValidationError",
    "AuthorizationDecision",
    "AuthorizationPort",
    "AuthorizationReceipt",
    "AuthorizationRequest",
    "AuthorizationResult",
    "CancellationToken",
    "CatalogRunToolExposure",
    "DuplicateToolCallError",
    "DuplicateToolError",
    "EffectExecution",
    "EffectKind",
    "EffectPolicy",
    "ExecutableToolRecord",
    "FunctionOutcomeParser",
    "EffectExecutor",
    "FunctionTool",
    "JsonObject",
    "LateToolResultError",
    "MalformedToolArgumentsError",
    "OutcomeParserPort",
    "PUBLIC_PROGRESS_ARGUMENT",
    "PreparedToolEffect",
    "ReconciliationObservation",
    "ReconciliationState",
    "ResourceScopeResolverPort",
    "RunToolExposurePort",
    "RunToolExposureState",
    "RuntimeCapabilityKind",
    "RuntimeCapabilityRecord",
    "RuntimeToolCatalog",
    "RuntimeToolCatalogError",
    "RuntimeToolCatalogSnapshot",
    "RuntimeToolDescription",
    "RuntimeToolDescriptor",
    "RuntimeToolSearchPage",
    "SchemaDefinitionError",
    "Sidecar",
    "SkillResourceRecord",
    "Tool",
    "ToolCall",
    "ToolCallState",
    "ToolAuthorizationPending",
    "ToolActivationReceipt",
    "ToolEffectClass",
    "ToolExecutionPolicy",
    "ToolContext",
    "ToolCompletionSemantics",
    "ToolDispatchKind",
    "ToolExposureMode",
    "ToolHandler",
    "ToolOutcome",
    "ToolOutcomeParser",
    "ToolResource",
    "ToolRouteRequirement",
    "ToolTaskScopeRequirement",
    "ToolInventoryRecord",
    "ToolReconciliationPort",
    "ToolRegistry",
    "ToolRegistryError",
    "ToolResult",
    "ToolSpec",
    "ToolSidecar",
    "UnknownToolError",
    "WorkflowProfileRecord",
    "bind_authorization_receipts",
    "builtin_outcome_parser",
    "sdk_authorization_receipt",
    "inventory_digest",
    "normalize_public_progress_arguments",
    "parse_tool_outcome",
    "resource_digest",
)
